language: go
go:
  - "1.12.4"

install:
  - go get github.com/gohugoio/hugo

git:
  depth: 1

notifications:
  email: false

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  repo: cube219/cube219.github.io
  target-branch: master
  committer-from-gh: true
  on:
    branch: master
