language: go
go:
  - "1.14"

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

install:
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git --depth=1 -b stable
  - cd hugo
  - go install --tags extended
  - cd /home/travis/gopath/src/github.com/Cube219/Blog

git:
  depth: 1

notifications:
  email: false

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  repo: cube219/cube219.github.io
  target-branch: master
  committer-from-gh: true
  on:
    branch: master
